icms/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('schedule/', include('schedule.urls')),
    path('', RedirectView.as_view(url='/schedule/login')),
] 

schedule/urls.py
from django.urls import path
from django.views.generic import RedirectView
from schedule import views

app_name = 'schedule'
urlpatterns = [
    path("login", views.login_mainpage, name="login"),
    path("logout", views.logout_mainpage, name="logout"),
    path("home", views.home_page, name="home"),
    path("send_to_email", views.send_upcoming_classes, name="send-to-email"),
    path("logs", views.view_logs, name="logs"),
    path("", RedirectView.as_view(url='/schedule/login'), name='go-to-login'),
]

schedule/models.py
from operator import truediv
from django.db import models
from django.db.models import CheckConstraint, Q,F
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError
from users.models import User

class Course(models.Model):
    code = models.CharField(max_length=11)
    name = models.CharField(max_length=100)
    offered = models.BooleanField()
    moodle_link = models.URLField()
    students = models.ManyToManyField(User, through="Enrolment")
    def __str__(self):
        return f"{self.code} {self.name}"

class Staff(models.Model):
    name = models.CharField(max_length=100)
    courses = models.ManyToManyField(Course, through="Teaching")
    
    def __str__(self):
        return f"{self.name}, ID {self.id}"

class Teaching(models.Model):
    class Roles(models.TextChoices):
        TUTOR = "T", _("Tutor")
        LECTURER = "L", _("Lecturer")
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    staff = models.ForeignKey(Staff, on_delete=models.CASCADE)
    role = models.CharField(max_length=1, choices=Roles.choices)

    def __str__(self):
        return f"{self.staff.name}, {self.course.code}, {self.role}"

class Enrolment(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.student.email} {self.course.code}"

class Class(models.Model):
    class WeekDays(models.TextChoices):
        MONDAY = "1", _("Monday")
        TUESDAY = "2", _("Tuesday")
        WEDNESDAY = "3", _("Wednesday")
        THURSDAY = "4", _("Thursday")
        FRIDAY = "5", _("Friday")
        SATURDAY = "6", _("Saturday")
        SUNDAY = "7", _("Sunday")

    class ClassTypes(models.TextChoices):
        TUTORIAL = "T", _("Tutorial")
        LECTURE = "L", _("Lecture")
    
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    class_id = models.IntegerField()
    location = models.CharField(max_length=100)
    class_day = models.CharField(max_length=3, choices=WeekDays.choices)
    start_time = models.TimeField()
    end_time = models.TimeField()
    class_type = models.CharField(max_length=1, choices=ClassTypes.choices)
    zoom_link = models.URLField(blank = True)
    teacher_message = models.CharField(max_length=1000, blank=True)

    def __str__(self):
        return f"{self.course.code}, {self.class_type}, {self.class_id}, {self.location}, {self.class_day}, {self.start_time}-{self.end_time}"

    def clean(self):
        if self.start_time > self.end_time:
            raise ValidationError({"start_time": _("Start time is after end time")})

    class Meta:
        unique_together = ['course', 'class_id']
        constraints = [
            CheckConstraint(
                name="valid_start_end_time",
                check=Q(start_time__lt=F("end_time"))
            )
        ]

schedule/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.core.mail import send_mail
from django.core.exceptions import ValidationError
from django.core.validators import validate_email
from django.conf import settings
from django.http import HttpResponse
from smtplib import SMTPException
from datetime import datetime, date, timedelta
from schedule.models import  Class, Enrolment, Course, Teaching
from users.models import User
import pytz
import math
from datetime import datetime

def login_mainpage(request):
    # redirect to home if the user has logged in already
    if request.user.is_authenticated:
        return redirect("/schedule/home")
    
    if request.POST:
        # if it's a face login
        if 'face_auth_mp4' in request.FILES or 'face_auth_webm' in request.FILES:
            user = authenticate(request=request)
            if user is None:
                context = {"error": "Face NOT recognized"}
                return render(request, 'schedule/login.html', context=context)
            
        # otherwise, it's a email-password login
        else:
            email = request.POST['email']
            password = request.POST['password']
            try:
                validate_email(email)
            except ValidationError:
                user = None
            else:
                user = authenticate(request=request, username=email, password=password)
            if user is None:
                context = {"error": "Incorrect email or password"}
                return render(request, 'schedule/login.html', context=context)
        
        # log user in and redirect to home if authentication passed
        login(request, user)
        return redirect("/schedule/home")

    return render(request, 'schedule/login.html')

@login_required
def logout_mainpage(request):
    # print the detailed log when users log out
    email = request.user.email
    # take last login time from the user's record
    last_login = request.user.last_login.astimezone(pytz.timezone("Asia/Hong_Kong"))
    
    # find the user's IP address from the request body
    remote_addr = request.META['REMOTE_ADDR']

    # take the current time
    time_now = datetime.now().astimezone(pytz.timezone("Asia/Hong_Kong"))
    
    # calculate the current duration since the user logged in
    duration = (time_now - last_login).total_seconds()

    # prepare the log list and render the page
    log_list = [
        {
            "content": f"{email} logged in from {remote_addr}",
            "timestamp": last_login.strftime('%d/%m/%Y %I:%M:%S %p')
        },
        {
            "content": f"{email} has been logged in for {duration:.2f} seconds",
            "timestamp": time_now.strftime('%d/%m/%Y %I:%M:%S %p')
        }
    ]
    context = {
        "log_list": log_list
    }
    logout(request)
    return render(request, "schedule/logout.html", context)

@login_required
def view_logs(request):
    email = request.user.email
    # take last login time from the user's record
    last_login = request.user.last_login.astimezone(pytz.timezone("Asia/Hong_Kong"))
    
    # find the user's IP address from the request body
    remote_addr = request.META['REMOTE_ADDR']

    # take the current time
    time_now = datetime.now().astimezone(pytz.timezone("Asia/Hong_Kong"))
    
    # calculate the current duration since the user logged in
    duration = (time_now - last_login).total_seconds()

    # prepare the log list and render the page
    log_list = [
        {
            "content": f"{email} logged in from {remote_addr}",
            "timestamp": last_login.strftime('%d/%m/%Y %I:%M:%S %p')
        },
        {
            "content": f"{email} has been logged in for {duration:.2f} seconds",
            "timestamp": time_now.strftime('%d/%m/%Y %I:%M:%S %p')
        }
    ]
    context = {
        "log_list": log_list
    }
    return render(request, "schedule/logs.html", context)

@login_required
def home_page(request):
   # get enrolled courses of user and its corresponding classes
    courses_enrolled = Course.objects.filter(students=request.user, offered=True)
    classes = Class.objects.filter(course__in=courses_enrolled).order_by('class_day')
   

    time_duration = [
        "9:30AM","10:00AM", "10:30AM","11:00AM", "11:30AM","12:00PM", "12:30PM","1:00PM", "1:30PM",
        "2:00PM", "2:30PM","3:00PM", "3:30PM","4:00PM", "4:30PM","5:00PM", "5:30PM", 
        "6:00PM", "6:30PM", "7:00PM", "7:30PM", "8:00PM", "8:30PM", "9:00PM", "9:30PM", "10:00PM" 
    ]
    time_formatted = [datetime.strptime(time,"%I:%M%p").time() for time in time_duration]
    
    # fetch classes into dictionary
    lectures = [
        {
            "code": class_ed.course.code,
            "name": class_ed.course.name,
            "weekday": class_ed.class_day,
            "row_span": 0,
            "start_time": class_ed.start_time,
            "end_time": class_ed.end_time,
            "location": class_ed.location,
            "type": class_ed.class_type,
            "moodle_link": class_ed.course.moodle_link
        } for class_ed in classes
    ]
  

    # calculate rowspan for each class
    for class_ed in lectures:
        dt = datetime.now()
        temp_start = datetime.combine(dt, class_ed["start_time"])
        temp_end = datetime.combine(dt, class_ed["end_time"])
        hour = temp_end - temp_start
        class_ed["row_span"] = math.ceil(hour.total_seconds() / 1800)
    timetablestr = ""
    
    # dictionary to hold how many next rows to skip at each weekday column
    weekday_skip_next_rows = {"1": 0, "2": 0, "3": 0, "4": 0, "5": 0}
    
    class_type ={"L": "Lecture", "T": "Tutorial"}
    for time in time_formatted:
        timetablestr += "<tr>"
        timetablestr += f"<th scope=\"row\">{time.strftime('%I:%M%p')}</th>"

        for days in range(1, 6):
            # flag for searching classes
            found = 0
            for lecture in lectures:
                if lecture["start_time"] == time and lecture["weekday"] == str(days): # class found
                    # skip the next (lecture's rowspan - 1) rows in the lecture's weekday column
                    weekday_skip_next_rows[lecture["weekday"]] += lecture["row_span"] - 1

                    # add the lecture entry to the timetable
                    timetablestr += f"<td rowspan=\"{lecture['row_span']}\">"
                    timetablestr += f"<div class = \"box\"><span><a href='{lecture['moodle_link']}'><b>{lecture['code']}</b></a>"
                    timetablestr += f"<br >{lecture['name']}<br />"
                    timetablestr += f"{lecture['start_time'].strftime('%I:%M %p')} - {lecture['end_time'].strftime('%I:%M %p')}<br />"
                    timetablestr += f"{lecture['location']}<br />"
                    timetablestr += f"{class_type[lecture['type']]}<br />"
                    timetablestr += f"</span></div></td>"
                    found = 1
                    break
            
            # if no class is found
            if found == 0:
                # check if the weekday row is to skip
                if weekday_skip_next_rows[str(days)] > 0:
                    # subtract one row as it is skipped
                    weekday_skip_next_rows[str(days)] -= 1
                    continue

                # otherwise print an empty weekday row
                else:
                    timetablestr += "<td></td>"

        # close a row i.e. a time period
        timetablestr += "</tr>"


    upcoming_classes = retrieve_upcoming_classes(request)

    context = {
        "last_login": request.user.last_login.astimezone(pytz.timezone("Asia/Hong_Kong")).strftime("%d/%m/%Y %I:%M %p"),
        "time_formatted": time_formatted,
        "timetablestr":timetablestr,
        "upcoming_classes": upcoming_classes,
    }
    
    return render(request, "schedule/home.html", context)

@login_required
def send_upcoming_classes(request):
    # retrieve upcoming classes
    upcoming_classes = retrieve_upcoming_classes(request)
    
    # do nothing if there is no upcoming class
    if len(upcoming_classes) == 0:
        return HttpResponse(content="No upcoming class.")

    # otherwise, prepare the email
    subject = "[COMP3278 HKU ICMS] You have class in ONE hour!"
    message = ""
    for upcoming_class in upcoming_classes:
        message += f"The class {upcoming_class['code']} {upcoming_class['name']} is starting soon.\n"
        message += f"Location: {upcoming_class['location']}\n"
        message += f"Time: {upcoming_class['start_time']} - {upcoming_class['end_time']}\n"
        message += f"Lecturer(s): {upcoming_class['lecturers']}\n"
        message += f"Tutor(s): {upcoming_class['tutors']}\n"
        if upcoming_class['teacher_message'] != "":
            message += f"Teacher's message: {upcoming_class['teacher_message']}\n"
        if upcoming_class['zoom_link'] != "":
            message += f"Zoom link: {upcoming_class['zoom_link']}\n"
        message += f"Course material: {upcoming_class['course_material']}\n\n"
    message += "Please DO NOT reply to this email.\n\n"
    message += "Regards,\nCOMP3278 HKU ICMS"
    
    # send the email
    try:
        send_mail(
            subject=subject,
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[User.objects.get(pk=request.user.id).email]
        )
    except SMTPException:
        return HttpResponse(content="FAILED to send email")

    return HttpResponse(content="Email sent SUCCESSFULLY.")

@login_required
def retrieve_upcoming_classes(request):
    result = []
    try:
        # Retrieve all user's enrolment
        user_all_enrolment = Enrolment.objects.filter(student=request.user, course__offered=True)
        # Get the course in each enrolment record

templates/schedule/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <header>
            <div id="" class="container"></div>
        </header>
        <main>
            <div id="content" class="container min-vh-100 py-3">
                {% block content %} {% endblock %}
            </div>
        </main>
        <footer class="text-center p-2">
            Created by COMP3278 Students
        </footer>
    </body>
</html>

templates/schedule/home.html
{% extends "schedule/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="d-flex justify-content-end">
    <div class="">
        <a href="{% url 'schedule:logout' %}">Logout</a>
    </div>
</div>
<div class="d-flex justify-content-between">
    <div class="">Welcome, {{ user.email|default:"None" }}</div>
    <div class="">
        Last Login: {{ last_login|default:"dd/mm/yyyy HH:MM:SS" }}
    </div>
</div>


<!-- this section will appear when there is class less than one hour -->
{% if upcoming_classes %}
{% for upcoming_class in upcoming_classes %}
<section>
    <div class="alert alert-primary" role="alert">
        You have class in less than one hour
    </div>
    <div>Course code: {{ upcoming_class.code|default:"Not specified" }}</div>
    <div>Course name: {{ upcoming_class.name|default:"Not specified" }}</div>
    <div>Location: {{ upcoming_class.location|default:"Not specified" }}</div>
    <div>Time: {{ upcoming_class.start_time }} - {{ upcoming_class.end_time  }}</div>
    {% if upcoming_class.lecturers %}
    <div>Lecturer(s): {{ upcoming_class.lecturers }}</div>
    {% endif %}
    {% if upcoming_class.tutors %}
    <div>Tutor(s): {{ upcoming_class.tutors }}</div>
    {% endif %}
    <div>
        Teacher's message: {{ upcoming_class.teacher_message|default:"Not specified" }}</div>
    <div>
        Zoom link:
        {% if upcoming_class.zoom_link %}
            <a href='{{ upcoming_class.zoom_link }}' target="_blank">{{ upcoming_class.zoom_link }}</a>
        {% else %}
            Not available
        {% endif %}
    </div>
    <div>
        Course material: 
        {% if upcoming_class.course_material %}
            <a href="{{ upcoming_class.course_material }}" target="_blank">{{ upcoming_class.course_material }}</a>
        {% else %}
            Not available
        {% endif %}
    </div>
    <button type="button" class="btn btn-primary" onclick="send_email()">Send to email</button>
    
</section>
{% endfor %}

{% endif %}

{% include "schedule/personal_timetable.html" %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
function send_email(){
    $.get('/schedule/send_to_email', function(message) {
        if (message == "No upcoming class.")
            $(location).attr("href", "/schedule/home");
        alert(message);
    });
}
</script>

{% endblock %}

templates/schedule/login.html
{% load static %}
<!DOCTYPE html>


<head>
    <title>COMP3278 Project</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'login/main.css' %}">
</head>

<body>
    <div class="container  my-5 mx-5">
        <div class="row">
            <div class="col-md-6 ">
                <img src="{% static 'login/night.png' %}" class="img-fluid" alt="night">
            </div>
            <div class="col-md-6 px-3">
                <h1 class="pt-5">COMP3278 HKU ICMS</h1>

                <h2>Sign In</h2>


                <form action="login" method="post" id="login_form" enctype ="multipart/form-data">
                    {% csrf_token %}
                    {% if error %}
                        <p style="color:red;">{{ error }}</p>
                    {% endif %}
                    <div class="form-row">
                        <div class="col-lg-10 mb-3">
                            <input type="text" name="email" class="form-control p-3" placeholder="Enter your HKU email">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-10 mb-3">
                            <input type="password" name="password" class="form-control p-3" placeholder="Enter your password">
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-10 my-3">
                            <button type="submit" class="btn btn-primary btn-block login_btn">Login</button>
                        </div>
                    </div>
                </form>
                <button type="button" class="btn btn-secondary" id="face_auth_button">Face ID</button>
                <video id="video" width="600" height="400" autoplay hidden></video>
            </div>
        </div>
</body>
<script>
var video = document.getElementById('video');
var recorder;
var face_video = [];
var video_type = MediaRecorder.isTypeSupported("video/mp4") ? "video/mp4" : "video/webm";

document.getElementById('face_auth_button').addEventListener("click", function() {
    if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia && video.hidden) {
        function capture() {
            video.pause();
            recorder.stop();
            video.srcObject.getTracks().forEach( (track) => { track.stop(); });
            video.hidden = !video.hidden;
        }
        navigator.mediaDevices.getUserMedia({ video: true }).then(function(stream) {
            video.srcObject = stream;
            
            recorder = new MediaRecorder(stream, { mimeType: video_type });
            video.play();
            recorder.start();
            video.hidden = !video.hidden;
            recorder.ondataavailable = (e) => { face_video.push(e.data); };
            recorder.onstop = (e) => {
                const video_blob = new Blob(face_video, { type: video_type });

                const face_auth_file = video_type == "video/mp4" ? new File([video_blob], "face_auth.mp4") : new File([video_blob], "face_auth.webm");
                const data_transfer = new DataTransfer();
                data_transfer.items.add(face_auth_file);

                var face_auth = document.createElement("input");
                face_auth.setAttribute("type", "file");
                if (video_type == "video/mp4")
                    face_auth.setAttribute("name", "face_auth_mp4");
                else face_auth.setAttribute("name", "face_auth_webm");
                face_auth.hidden = true;
                face_auth.files = data_transfer.files;
                document.getElementById("login_form").appendChild(face_auth);
                document.forms["login_form"].submit();
            };
            setTimeout(capture, 2000);
        });
    }
});
</script>
<!-- Links for the logos
    clouds
https://www.flaticon.com/free-icon/cloud-computing_892300?term=cloud%20computing&page=1&position=23&page=1&position=23&related_id=892300&origin=tag
https://www.flaticon.com/free-icon/clouds_414927?term=cloud&page=1&position=2&page=1&position=2&related_id=414927&origin=search
Moon
https://www.flaticon.com/free-icon/moon_1823324?term=moon&page=1&position=6&page=1&position=6&related_id=1823324&origin=search
-->

templates/schedule/logout.html
{% extends "schedule/base.html" %}

{% block title %}Logout{% endblock %}

{% block content %}
<div class="d-flex justify-content-end">
    <div>
        <a href="{% url 'schedule:login' %}">Login</a>
    </div>
</div>
<p class="text-center">See you again. This is the log of your last session</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Contents</th>
            <th scope="col">Timestamps</th>
        </tr>
    </thead>
    <tbody>
        {% for log in log_list %}
        <tr>
            <td>{{ log.content }}</td>
            <td>{{ log.timestamp }}</td>
        </tr>
        {% empty %}
        <tr>
            <th scope="row" colspan="3" class="text-center">There is no logs to view</th>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>

    </tfoot>
</table>
{% endblock %}

templates/schedule/logs.html
{% extends "schedule/base.html" %}

{% block title %}Logs{% endblock %}

{% block content %}
<div class="d-flex justify-content-end">
    <div>
        <a href="{% url 'schedule:home' %}">Home</a>
    </div>
</div>
<div class="d-flex justify-content-end">
    <div>
        <a href="{% url 'schedule:logout' %}">Logout</a>
    </div>
</div>
<p class="text-center">Welcome to the log page</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Contents</th>
            <th scope="col">Timestamps</th>
        </tr>
    </thead>
    <tbody>
        {% for log in log_list %}
        <tr>
            <td>{{ log.content }}</td>
            <td>{{ log.timestamp }}</td>
        </tr>
        {% empty %}
        <tr>
            <th scope="row" colspan="3" class="text-center">There is no logs to view</th>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>

    </tfoot>
</table>
{% endblock %}

templates/schedule/personal_timetable.html
{% block content %}
{%load static%}
<link rel="stylesheet" href="{% static 'home/timetable.css' %}">
<p class="text-center">Timetable</p>
<table class="table" style="table-layout:auto;">
  <colgroup>
    <col span="1" style="background-color:grey">
    <col span="5" style="background-color:whitesmoke">
  </colgroup>
  <thead>
    <tr>
      <th scope="col">Time</th>
      <th class="weekday" scope="col">Monday</th>
      <th class="weekday" scope="col">Tuesday</th>
      <th class="weekday" scope="col">Wednesday</th>
      <th class="weekday" scope="col">Thursday</th>
      <th class="weekday" scope="col">Friday</th>
    </tr>
  </thead>
  <tbody>
    {{timetablestr|safe}}
  </tbody>
  <tfoot></tfoot>
</table>

{% endblock %}